apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tranquil-pds-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.vault.key }}
        property: db_password
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.vault.key }}
        property: jwt_secret
    - secretKey: DPOP_SECRET
      remoteRef:
        key: {{ .Values.vault.key }}
        property: dpop_secret
    - secretKey: MASTER_KEY
      remoteRef:
        key: {{ .Values.vault.key }}
        property: master_key
    - secretKey: SSO_OIDC_CLIENT_ID
      remoteRef:
        key: {{ .Values.vault.key }}
        property: authentik_id
    - secretKey: SSO_OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.vault.key }}
        property: authentik_secret
