apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.imagePullSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.vault.key }}
        property: dockerconfigjson
