apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranquil-pds-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.app.storage }}
