---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - ./resources/limiter.toml
      - ./resources/settings.yml
generatorOptions:
  disableNameSuffixHash: true
