apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: indexer-cred
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: indexer-cred
    creationPolicy: Owner
  data:
    - secretKey: INDEXER_USERNAME
      remoteRef:
        key: wazuh
        property: indexer_username
    - secretKey: INDEXER_PASSWORD
      remoteRef:
        key: wazuh
        property: indexer_password
    - secretKey: INDEXER_PASSWORD_HASH
      remoteRef:
        key: wazuh
        property: indexer_password_hash
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dashboard-cred
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dashboard-cred
    creationPolicy: Owner
  data:
    - secretKey: DASHBOARD_USERNAME
      remoteRef:
        key: wazuh
        property: dashboard_username
    - secretKey: DASHBOARD_PASSWORD
      remoteRef:
        key: wazuh
        property: dashboard_password
    - secretKey: DASHBOARD_PASSWORD_HASH
      remoteRef:
        key: wazuh
        property: dashboard_password_hash
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wazuh-api-cred
    creationPolicy: Owner
  data:
    - secretKey: API_USERNAME
      remoteRef:
        key: wazuh
        property: api_username
    - secretKey: API_PASSWORD
      remoteRef:
        key: wazuh
        property: api_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wazuh-authd-pass
    creationPolicy: Owner
  data:
    - secretKey: "authd.pass"
      remoteRef:
        key: wazuh
        property: authd_pass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-oidc-cred
  namespace: wazuh
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wazuh-oidc-cred
    creationPolicy: Owner
  data:
    - secretKey: OPENSEARCH_OIDC_CLIENT_ID
      remoteRef:
        key: wazuh
        property: oidc_client_id
    - secretKey: OPENSEARCH_OIDC_CLIENT_SECRET
      remoteRef:
        key: wazuh
        property: oidc_client_secret
