apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  source:
    repoURL: https://rubxkube.github.io/charts/
    targetRevision: 0.3.2
    chart: cloudflare-tunnel
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            cloudflare:
              tunnelName: "home-cluster"
              tunnelId: "2f3b093d-bd57-4708-8d54-42723da21338"
              secretName: "cloudflare-tunnel"
              ingress:
                - hostname: "*.<path:kv/cloudflared#domain>"
                  service: "https://traefik.traefik.svc.cluster.local:443"
                  originRequest:
                    noTLSVerify: true

            resources:
              limits:
                cpu: "100m"
                memory: "128Mi"
              requests:
                cpu: "100m"
                memory: "128Mi"

            replicaCount: 1
