apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: qjoly
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: qjoly
  validation: client
