apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-une-tasse-de.cafe
  namespace: default
spec:
  secretName: wildcard-une-tasse-de.cafe
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer 
  commonName: "*.une-tasse-de.cafe"
  dnsNames:
  - "une-tasse-de.cafe"
  - "*.une-tasse-de.cafe"
