apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-une-pause-cafe
  namespace: default
spec:
  secretName: wildcard-une-pause-cafe
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer 
  commonName: "*.une-pause-cafe.fr"
  dnsNames:
  - "une-pause-cafe.fr"
  - "*.une-pause-cafe.fr"
