apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  source:
    repoURL: https://rubxkube.github.io/common-charts/
    chart: common
    targetRevision: v0.6.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
              name: "vaultwarden"
              image:
                repository: vaultwarden/server
                tag: "1.36.0"
              service:
                servicePort: 80
                containerPort: 80
              deployment:
                port: 80
              ingress:
                enabled: true
                hostName: "vaultwarden.mocha.thoughtless.eu"
                ingressClassName: traefik
                tls:
                  enabled: true
                  secretName: "vaultwarden-tls"
                annotations:
                  cert-manager.io/cluster-issuer: cloudflare
              variables:
                secret:
                  existingSecret:
                    - envName: ADMIN_TOKEN
                      name: vaultwarden-secrets
                      key: admin_token
                nonSecret:
                  DOMAIN: "https://vaultwarden.mocha.thoughtless.eu"
                  SIGNUPS_ALLOWED: "false"
              extraResources:
                - apiVersion: external-secrets.io/v1
                  kind: ExternalSecret
                  metadata:
                    name: vaultwarden-secrets
                  spec:
                    refreshInterval: "1h"
                    secretStoreRef:
                      name: vault-backend
                      kind: ClusterSecretStore
                    target:
                      name: vaultwarden-secrets
                      creationPolicy: Owner
                    data:
                      - secretKey: admin_token
                        remoteRef:
                          key: vaultwarden
                          property: admin_token
              persistence:
                enabled: true
                volumes:
                  - name: data
                    storageClassName: ""
                    size: 5Gi
                    pvcClaim: ""
                    containerMount: "/data"
