apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-credentials
  namespace: plex-exporter
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plex-credentials
    creationPolicy: Owner
  data:
    - secretKey: PLEX_SERVER
      remoteRef:
        key: plex
        property: server
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: plex
        property: token
