apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-vaults-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: ghcr.io/bank-vaults/helm-charts
    chart: vault-operator
    targetRevision: 1.24.0
    helm:
      values: |
        watchNamespace: ""
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: bank-vaults
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
