apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-cortado
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.10.1
      helm:
        values: |
          githubConfigUrl: "https://github.com/qjoly"
          githubConfigSecret:
            github_app_id: 1138353
            github_app_installation_id: 62973612
            github_app_private_key: |
              <path:kv/github-runner#private_key | indent 3>


          controllerServiceAccount:
            name: arc-gha-rs-controller
            namespace: arc

          storage:
            enabled: true
            requests: 5Gi

          podSecurityContext:
            fsGroup: 2000

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: arc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
