apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.11.0
      helm:
        values: |
          storage:
            enabled: true
            requests: 5Gi

          podSecurityContext:
            fsGroup: 2000

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: arc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
