---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
  namespace: rook-ceph 
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph
      version: "v1.12.9"
      sourceRef:
        kind: HelmRepository
        name: rook-charts
        namespace: flux-system
