apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rmfakecloud
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rmfakecloud
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: rmfakecloud
        property: jwt_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: smtp_password
      remoteRef:
        key: rmfakecloud
        property: smtp_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
