apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik
        property: secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: authentik
        property: pg_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgres-password
      remoteRef:
        key: authentik
        property: pg_admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
