apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atcr-hold-s3
  namespace: atcr-hold
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: atcr-hold-s3
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: atcr-hold
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: atcr-hold
        property: secret_key
