apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: jellyfin
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/InfoTech/Formations
    server: 192.168.1.90
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: local
