repositories:
  - name: cilium
    url: https://helm.cilium.io/

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: "1.19.5"
    values:
      - helm/cilium/values.yaml
