apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kromgo.yaml
configMapGenerator:
  - name: kromgo-configmap
    namespace: monitoring
    files:
      - config.yaml=./config.yaml
generatorOptions:
  disableNameSuffixHash: true
