repos:
- repo: local
  hooks:
    - id: encrypt files
      name: encrypt files
      entry: .scripts/.pre-commit-sops.sh
      language: script
      pass_filenames: true
      verbose: true
      always_run: true
- repo: https://github.com/sirosen/fix-smartquotes
  rev: 0.1.1
  hooks:
    - id: fix-smartquotes
