creation_rules:
  - path_regex: talos/.*/.*
    encrypted_regex: '((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))'
    key_groups:
      - age:
          - age14ysm820ajay8wqslnkjqcewvq4tmeucth3a88qk4a7hl0mnwkfaqmj6xx5

  - path_regex: secret.*\.ya?ml
    encrypted_regex: "^(username|password|node_url|root_password)$"
    key_groups:
      - age:
          - age14ysm820ajay8wqslnkjqcewvq4tmeucth3a88qk4a7hl0mnwkfaqmj6xx5
