# https://taskftaile.dev

version: '3'

vars:
  secret_file: ./secret.dev.yaml
  hypervisor: Proxmox # for now, only proxmox is available
  distribution: Debian 
  distribution_version: 11

includes:
  general:
    taskfile: ./.taskfiles/general.yml
    optional: false

  packer:
    taskfile: ./.taskfiles/packer.yml
    optional: false
