# https://taskftaile.dev

version: '3'

vars:
  secret_file: ./secret.dev.yaml
  hypervisor: Libvirt # for now, only proxmox is available
  distribution: Debian 
  
includes:
  general:
    taskfile: ./.taskfiles/general.yml
    optional: false

  packer:
    taskfile: ./.taskfiles/packer.yml
    optional: false

  terraform:
    taskfile: ./.taskfiles/terraform.yml
    optional: false

  kubernetes:
    taskfile: ./.taskfiles/kubernetes.yml
    optional: false
