apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blueprince-helper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/briangtn/blue-prince-note-helper.git
    targetRevision: main
    path: chart
    helm:
      values: |
        image:
          repository: ghcr.io/briangtn/blue-prince-note-helper
          tag: v1.0.0
          pullPolicy: IfNotPresent
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
          hosts:
            - host: "blueprince.lucca.bar"
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: blueprince-helper-tls
              hosts:
                - "blueprince.lucca.bar"
        auth:
          roUser: viewer
          rwUser: admin
        persistence:
          enabled: true
          size: 1Gi
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  destination:
    server: https://kubernetes.default.svc
    namespace: blueprince-helper
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
