apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.3.0
    chart: traefik
    helm:
      values: |
        service:
          annotations:
            lbipam.cilium.io/sharing-key: "public"
            lbipam.cilium.io/sharing-cross-namespace: "*"
        ports:
          websecure:
            transport:
              respondingTimeouts:
                readTimeout: 300
                writeTimeout: 300
                idleTimeout: 300
              lifeCycle:
                requestAcceptGraceTimeout: 300
                graceTimeOut: 300
              keepAliveMaxRequests: 100
              keepAliveMaxTime: 300