apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbird
    creationPolicy: Owner
  data:
    - secretKey: relayPassword
      remoteRef:
        key: netbird
        property: relay_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: datastoreEncryptionKey
      remoteRef:
        key: netbird
        property: datastore_encryption_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: turnPassword
      remoteRef:
        key: netbird
        property: turn_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
