apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matomo-db
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: matomo-db
    creationPolicy: Owner
  data:
    - secretKey: db_password
      remoteRef:
        key: matomo
        property: db_password
    - secretKey: db_root_password
      remoteRef:
        key: matomo
        property: db_root_password
