apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    chart: csi-driver-nfs
    targetRevision: 4.13.4
    helm:
      values: |
        storageClass:
          create: true
          name: nfs-turing
          parameters:
            server: 192.168.0.143
            share: /mnt/Stockage/Kubernetes
            mountPermissions: "0"
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          mountOptions:
            - nfsvers=4.1
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-driver-nfs
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
