apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  source:
    repoURL: https://bjw-s.github.io/helm-charts/
    chart: app-template
    targetRevision: 3.7.0
    helm:
      values: |
        controllers:
          renovate:
              containers:
                app:
                  image:
                    repository: renovate/renovate
                    tag: 39.104.1
                    pullPolicy: IfNotPresent
                  env:
                    LOG_LEVEL: debug
                    GITHUB_COM_TOKEN: "<path:kv/renovate#github>"
                    RENOVATE_TOKEN: "<path:kv/renovate#github>"
                    RENOVATE_PLATFORM: 'github'
                    RENOVATE_GIT_AUTHOR: 'unetassedecafe <github_second@une-pause-cafe.fr>'
                    RENOVATE_CONFIG_FILE: '/opt/renovate/config.json'
                  resources:
                    requests:
                      cpu: 250m
                      memory: 500Mi
                    limits:
                      cpu: '2'
                      memory: 4Gi
        service:
          renovate:
            controller: renovate
            ports:
              http:
                port: 8080
        persistence:
          config:
            enabled: true
            type: configMap
            name: renovate-config
            globalMounts:
              - path: /opt/renovate/config.json
                subPath: config.json
          cache:
            enabled: true
            type: emptyDir
            globalMounts:
              - path: /tmp/renovate
        ingress:
          renovate:
            enabled: true
            className: nginx
            hosts:
              - host: "renovate.<path:kv/cluster#domain>"
                paths:
                  - path: /
                    service:
                      identifier: renovate
                      port: http
            tls:
              - secretName: renovate-tls
                hosts:
                  - "renovate.<path:kv/cluster#domain>"
        configMaps:
          config:
            enabled: true
            data:
              config.json: |-
                {
                  "autodiscoverFilter": "/qjoly/",
                  "autodiscover": true
                }
