apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: kyoo
    targetRevision: 0.1.8
    helm:
      values: |
        postgresql:
          enabled: true
          auth:
            password: "<path:kv/kyoo#dbpassword>"
        volumes:
          media:
            enabled: false
        secrets:
          kyoo:
            enabled: true
            name: "kyoo-secrets"
            data:
              kyoo-apikeys: "<path:kv/kyoo#apikey>"
              tmdb-api: "<path:kv/kyoo#tmdb>"
        config:
          name: "kyoo-config"
          enabled: true
          data:
            LIBRARY_LANGUAGES: "fr"
            LIBRARY_IGNORE_PATTERN: "/data/Formations/.*"
        ingress:
          enabled: true
          hostName: "kyoo.<path:kv/cluster#domain>"
          ingressClassName: "traefik"
          extraLabels: {}
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: front
                  port:
                    number: 8901
            - path: /api
              pathType: Prefix
              backend:
                service:
                  name: back
                  port:
                    number: 5000
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            external-dns.alpha.kubernetes.io/hostname: "kyoo.<path:kv/cluster#domain>"
            external-dns.alpha.kubernetes.io/target: <path:kv/cloudflare#tunnelid>.cfargotunnel.com
          tls:
            enabled: true
            secretName: "kyoo-tls"
        back:
          deployment:
            memoryLimit: "4000Mi"
            cpuLimit: ""
        matcher:
          deployment:
            memoryLimit: "1000Mi"
            cpuLimit: "2000m"

        extraResources:
          - apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: nfs-kyoo
            spec:
              capacity:
                storage: 100Gi
              volumeMode: Filesystem
              accessModes:
                - ReadOnlyMany
              persistentVolumeReclaimPolicy: Retain
              storageClassName: local
              mountOptions:
                - hard
                - nfsvers=4.1
              nfs:
                path: /mnt/Stockage/Plex
                server: 192.168.1.90
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: media
            spec:
              accessModes:
                - ReadOnlyMany
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 100Gi
              storageClassName: local
  destination:
    server: https://kubernetes.default.svc
    namespace: kyoo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
