apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# blueweave-secrets (app env) is still created by hand in the namespace.
resources:
  - namespace.yaml
  - externalsecret.yaml
  - config.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - podmonitor.yaml

images:
  - name: atcr.io/une-tasse-de.cafe/blueweave
    newTag: main
