apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 2.2.14
    helm:
      values: |
        reloader:
          watchGlobally: true
          reloadStrategy: annotations
          deployment:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
          readOnlyRootFileSystem: true
          podMonitor:
            enabled: false
          serviceMonitor:
            enabled: false
