apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: 0.12.0
    helm:
      values: |
        controllers:
          main:
            containers:
              main:
                env:
                  DB_HOSTNAME: immich-postgres
                  DB_PORT: "5432"
                  DB_USERNAME: immich
                  DB_DATABASE_NAME: immich
                  DB_PASSWORD:
                    valueFrom:
                      secretKeyRef:
                        name: immich-db-credentials
                        key: password

        immich:
          persistence:
            library:
              existingClaim: immich-library
          configurationKind: Secret
          existingConfiguration: immich-oauth-config

        valkey:
          enabled: true

        server:
          enabled: true
          ingress:
            main:
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: cloudflare
                external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
                external-dns.alpha.kubernetes.io/hostname: immich.thoughtless.eu
                external-dns.alpha.kubernetes.io/target: "58c15097-f3b2-4ff7-a676-21bbeeea39d7.cfargotunnel.com"
              hosts:
                - host: immich.thoughtless.eu
                  paths:
                    - path: "/"
                      service:
                        identifier: main
              tls:
                - secretName: immich-tls
                  hosts:
                    - immich.thoughtless.eu

        machine-learning:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
