apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-oauth-config
  namespace: immich
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-oauth-config
    creationPolicy: Owner
  data:
    - secretKey: immich-config.yaml
      remoteRef:
        key: immich
        property: oauth_config
