apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-credentials
  namespace: immich
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: immich
        property: db_password
