apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2026.5.4
      helm:
        values: |
          authentik:
            error_reporting:
              enabled: false
          global:
            env:
              - name: AUTHENTIK_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: authentik-secrets
                    key: AUTHENTIK_SECRET_KEY
              - name: AUTHENTIK_POSTGRESQL__PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: authentik-secrets
                    key: password
          server:
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: cloudflare
              hosts:
                - authentik.mocha.thoughtless.eu
              tls:
                - secretName: authentik-tls
                  hosts:
                    - authentik.mocha.thoughtless.eu
          postgresql:
            enabled: true
            auth:
              existingSecret: authentik-secrets
              secretKeys:
                userPasswordKey: password
                adminPasswordKey: postgres-password
            primary:
              persistence:
                enabled: true
                storageClass: openebs-lvmpv
                size: 8Gi
    - repoURL: https://github.com/qjoly/gitops.git
      targetRevision: HEAD
      path: mocha/system/authentik/manifests
