apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://rubxkube.github.io/common-charts/
      chart: common
      targetRevision: v0.6.0
      helm:
        values: |
          name: "byparr"
          image:
            repository: ghcr.io/thephaseless/byparr
            tag: "latest"
          deployment:
            port: 8191
          service:
            containerPort: 8191
    - repoURL: https://rubxkube.github.io/charts/
      chart: jackett
      targetRevision: 1.4.0
      helm:
        values: |
          common:
            ingress:
              enabled: true
              annotations:
                external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
                external-dns.alpha.kubernetes.io/hostname: "indexer.thoughtless.eu"
                external-dns.alpha.kubernetes.io/target: "58c15097-f3b2-4ff7-a676-21bbeeea39d7.cfargotunnel.com"
              hostName: "indexer.thoughtless.eu"
              ingressClassName: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
