apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: joplin
    namespace: joplin
spec:
    interval: 15m
    chart:
        spec:
            chart: joplin
            version: '>=1.0.16'
            sourceRef:
                kind: HelmRepository
                name: rubxkube-charts
                namespace: flux-system
    values:
        define: 22300
        postgresql:
            enabled: true
            primary:
                readinessProbe:
                    initialDelaySeconds: 60
            auth:
                postgresPassword: changeme
                database: joplin
                username: joplinuser
                password: ENC[AES256_GCM,data:YoXFiy5zHYwS6lrOgwM=,iv:8H8yjxBmlTqIdqEYRz2rka52T0yCKw/aKVtlCB503Mw=,tag:vSWH2ciPVtqiiHmxZfpq5g==,type:str]
            persistence:
                enabled: true
                existingClaim: ""
                storageClass: ""
                size: 8Gi
        common:
            app:
                servicePort: 80
                containerPort: 22300
            # deployment
            deployment:
                memoryRequest: null
                cpuRequest: null
                memoryLimit: null
                cpuLimit: null
                strategy:
                    type: Replace
            # container
            image:
                repositorySettings:
                    isPrivate: false
                    secretName: null
                repository: joplin/server
                tag: 2.14-beta
                pullPolicy: Always
            # ingress
            ingress:
                enabled: false
                hostName: joplin.une-tasse-de.cafe
                tls:
                    enabled: true
                    secretName: ""
                # For Ingress CRD
                ingressClassName: istio
                # For IngressRoute CRD
                isIngressRoute: true
                entrypoint: websecure
                # leave empty if you don't use, tls.enabled must be true and secretName must me empty
                certResolver: letsencrypt
            # env variables
            variables:
                secret: {}
                nonSecret:
                    DB_CLIENT: pg
                    POSTGRES_DATABASE: joplin
                    POSTGRES_USER: joplinuser
                    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0bEnqgIRMwLsvG2+gFY=,iv:pDOZlKuZjQmC8LrIgA8uPubJ6Y2MUrAc2mkTSlseXAk=,tag:GRClXTy51QWEz6Wt1oQtGQ==,type:str]
                    # if postgresql.enabled, must be RELEASE-NAME-postgresql (ex: my-wakapi-postgresql)
                    POSTGRES_HOST: joplin-postgresql
                    POSTGRES_PORT: "5432"
                    APP_BASE_URL: https://joplin.une-tasse-de.cafe
            # horizontal autoscaler
            hpa:
                enabled: false
                minReplicas: 1
                maxReplicas: 2
                avgCpuUtilization: 50
            # startupProbe
            startupProbeEnabled: false
            startupProbe:
                httpGet:
                    path: /
                    port: 22300
                periodSeconds: 10
                failureThreshold: 20
                timeoutSeconds: 1
            # readinessProbe
            readinessProbeEnabled: true
            readinessProbe:
                tcpSocket:
                    port: 22300
                initialDelaySeconds: 30
                periodSeconds: 30
                failureThreshold: 2
                timeoutSeconds: 3
            # livenessProbe
            livenessProbeEnabled: true
            livenessProbe:
                tcpSocket:
                    port: 22300
                initialDelaySeconds: 30
                periodSeconds: 60
                failureThreshold: 1
                timeoutSeconds: 3
            persistence:
                # no need for persistence if you use postgresql
                enabled: false
            tests:
                # default helm test method
                classicHttp:
                    enabled: false
                # curl using ingress.hostName as Host in header
                curlHostHeader:
                    enabled: true
                    path: /api/ping
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9z8z69fa63fa8pnxklq00e8k3556sc233wlp20na7cykthtgvgqwnvej5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbE00bFdrbC9NNGJZVTNI
            Ky9PZkNSekxkbUtVbzNlNFVNcHpVVEtSSkVBClhjVlFpTEdNNkZPcnlFYzdseVQ4
            dVREaVJINkcraFVvOGVaSURKd1U5ZUUKLS0tIEEzTEdUNlJxVXNMZDVTVXZyYVBr
            d1BmTlRPZFd2SUZPak5aOU9KTkt4bk0K2VNnE2T/FyKD5zxLAEYTBqJW48q/lkx1
            fPAXjXmGmPAJqcImdlPxJorBr2sozioL5Ivb3xfQgCjr1K2si6NOkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ysm820ajay8wqslnkjqcewvq4tmeucth3a88qk4a7hl0mnwkfaqmj6xx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUXQ1UXZkVy9LWnVqMFlr
            eFFmcEF5Wmt2OVdWTGdsUUVMR3NrTkxxZDJBCmlzYW10V1ZUbTF4MklNcmlzYkNh
            dlBnZml3MWJZSkg5bHREWDRHaWdrNVUKLS0tIG5uR3RsYVcyVkh4d0pwdFUyVHIw
            Z1NzUVMzdTNrZmlvQkZGTHd2NGhuTFUKxCYUPG2kd4WeNTiKyFnEHsRQlhyxWzUR
            NUArLRCkedfmiDPL0B+JC6Uiedvlj797m6ICkdn4x90GG7OVgs/+Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T17:32:33Z"
    mac: ENC[AES256_GCM,data:4VuuuPjbH57F/0UdhIoLWEeuilefPsXRjbYQY0mv8iVIVSCSy0tXKTKI7vxxZB0g/WSh7SGdNlMogvPIQ+yAj0kfAhqC+thtE448819J/jREU3ohxfEALKmhTKMb/rVB02O2DeZCPTJBUBC2hlv9osWavypCfJAVhAkFW3dClh8=,iv:I9gP83BTVUWjRLLvptfL6F0SyBdLqfxZAfFqAbBihMI=,tag:goN9sFP6Z4W5vgmbvKC5LA==,type:str]
    pgp: []
    encrypted_regex: ^(password|POSTGRES_PASSWORD)$
    version: 3.8.1
