apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: flaresolverr
    targetRevision: 0.0.1
    helm:
      values: |
        common:
          image:
            repository: 21hsmw/flaresolverr
            tag: nodriver
            pullPolicy: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett
  syncPolicy:
    automated:
      prune: true