apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: jackett
    targetRevision: 1.3.1
    helm:
      values: |
        common:
          ingress:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
              external-dns.alpha.kubernetes.io/hostname: jackett.thoughtless.eu
              external-dns.alpha.kubernetes.io/target: 2f3b093d-bd57-4708-8d54-42723da21338.cfargotunnel.com
            hostName: jackett.thoughtless.eu
            ingressClassName: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
