apiVersion: v1
data:
    alertmanager.yml: ENC[AES256_GCM,data:yR/q9dZkChOpnJ3SF/brrCtULYI/qXBCf08bRT2qb7qgBumu8KTQUrzylJmZlMAYMrG/phl2St0JmwoukzOw+LRERTpibct1zqvVXayiFTSRF5d5J0T97BTev7zKJonYfz4zqwZTsesngYGixcuHPC8V9HAH+fl8puMIasZDDxK3ikT8XMgG/8Se01M4v75v3vecAhMiBqfmpbgs34RsC0SQNj7TNSCq87RoOuWgJbIfzjOyWVDJBadD8UgPARKk8zFK30aHct6H212gdJqkJ/f/YYOe1HpA/Yli1HsnH+/w2FyaK1+Ow8oIwA2exE29QDq22XWJfYiC6zdwhcPgggdvi2307Y7qryG0PHBo5LD1+xxGTHDisePbnPjki9BseoqHh5x6Z8Qa7RwfRyltdRhOZ9DynOQCPToJLxUhFd1MhfX142Y0VrIWUglaIbxbb0DfW0jw2c+pjPjD9TVGhkzw5i2d0Q9HKmTooIg4kzFXhTG6VtH/haAtQlKYEw/5qeV4E9fb4tOlZ4lQ947qGNvEvkWzLbmX4yz64XUgVHjdmYYZ437xOXm0FEqukP0bn9H9WQs14IGDO+5NMuJd7/ohrPlM/dc6vNl2AE4B+3XhG96hNgjlCgQ6fF6CIqf9lusd7lfzaOL7xnToV6HT9yrD03H2MHwGuNts1qXdoB3nzUnENxbyIWxSdfubIY/6wRoI+rUk6KQ7DcxkthI7yv1uPMop4PMU9nAkFCZ5rxYjkYx7keoxdZwiLhN0BNy1yGGmKNtp1I8mVk+oTPTBOkPh7lJF6yGO3ZCLlWxqcz/+QEOqDE8o4XbnvhUD3mZZJSqwmS8vU/nWI/JS8jsBuqB0ZjOvKe96D1bjNps7as+I5F+Z49Wk1A==,iv:Zlw1AE8ccLGgzjggIFc+TNwTgu2nNXrJ5VWWEMMUcSU=,tag:gOfgPA5hvtF8JFoUkjMu4g==,type:str]
kind: ConfigMap
metadata:
    annotations:
        meta.helm.sh/release-name: loki-stack
        meta.helm.sh/release-namespace: monitoring
    labels:
        app: prometheus
        app.kubernetes.io/managed-by: Helm
        component: alertmanager
        helm.toolkit.fluxcd.io/name: loki-stack
        helm.toolkit.fluxcd.io/namespace: monitoring
        heritage: Helm
        release: loki-stack
    name: loki-stack-prometheus-alertmanager
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9z8z69fa63fa8pnxklq00e8k3556sc233wlp20na7cykthtgvgqwnvej5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTE9kL3hqUHJtczVFdGI5
            SXFlWkJzSlY2aHprY2lGYzN6VEdyemloYUNNCm1CY1NyZ2xNQjNjcStMZG9TRDBn
            QTZadDVlUWIzc0pwbTRNeDRCd20xcU0KLS0tIEtkMWlKVmtRU01ZaHMyWkYzcnho
            YmgvK1R5cXJQSEo3c3o2ZVEyQ1lnWk0KE79gtBbyqecAw3hgb5wBvjljF/kctQt0
            lhqZ18OO8YFDUDGEfKQf5kyC4XNL0KKknqu/CZ6zjnV/Bt1C5F65hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T06:39:34Z"
    mac: ENC[AES256_GCM,data:mietdXQms0XwD9HenpaTC7qIdhNIhFalPHYaE+AyZbh92aLjGboAzCIxBv+OYjEFplLBZ6tXJ2h7tgKkyLAy/IODiecTngOFIJ3wibZ73vkqKWBv1H4v6gcENF4j6k3pyWM4KWKcf72mmgaWQm8p0i2YT88ciLFsBlZXRz260IM=,iv:Czd2IGE0Oi6zjG+Ynn11e3tF7MTE0P+apOPpv879SYc=,tag:GM5J/FM1eMbg+IehWyf4kQ==,type:str]
    pgp: []
    encrypted_regex: ^(alertmanager.yml)$
    version: 3.8.1
