apiVersion: v1
data:
    alertmanager.yml: ENC[AES256_GCM,data:LqXG3zId6AxoUqu+lVkaytal+45OqYSk6Q9TqPTUroj8lNT8iMKbDAgZAzuUePRBgd0D1z1Zbby0T2KeSqbPQvLJ/f13Wj5f7oyPD0fbQPv15iU8tifIZkTrd0ugcn+mD2nkAq1HlAC9VMpsCSYsm81O+RieObxF2NefpdLCwLETX87+bevhW620vRZlLY+jrJaIET6liSmM7hIqOBaoMTimrHNISg9skELc0y8SN0rHK9w0PdpMOQ73y/8O/uJuOCft/lPpK19UJsXa913PcigZw6NZafEP9h0QC8Qw+yFaIa+WMAtbsZMU8jX8VPp7VPonORV6j3hOZY5yGiL+vhnbeh5kcgI2ydbH1Yk5wn05jKdcAyEkytPAOpxCwfH+Sv8vFbU3H48BHwcagjU9yf1hyCllg6etRHJZFf+X1Tj6QnN7bxob53JmoXGt5Ui/KWl+foyqEFIcSifruonqlh45M5L0V3By3CdsEcZkorm7c6o6UGE4g2KQtXgdikIR69DENTB1HrmwCkUlmy5XZUfniqx8iKPEb6CcmMuMJT61pTcSPAWfzlk4vIxogE5o9TeVEWYCBV2f5EShlKLYRt7EpiYTryfYQqcb8s2Ipb2WN5WfwJUUN3FxBSgquxR5aq9HafmTEBdo7KNYQiOZf3Y8cb0FvKGLzqro8wV769247/u3Yd52+KJ0nALsVWAcegt/Mel29eCSCnpm1uK8Q0S9gUYpja62zI/wJ9QJOpIisneQ2uXIIC8mHbuBMlW2vqQo1B0glA0QYkUr+oeQSpFW/UyRDWmdaGiK5Ro9MTOWWI3kyfz2u3+1tKowVb9t3rA5sFfDu6FPWZyyakxOo/la55M7cNaxSf3lFis2Aqe95ON/vvYW2ONKwKlXxM9CqmvVxwBaZ9rtm/0ytPZdCGbbQEy8PjKYr0NBxZqkTCdJ+pLCUFF/F7eTV4ELKtIIFDgM,iv:It1xw9oy9RFhEf7sFqd5kCDOWYTUtmGw2PtBsx5rRak=,tag:ZtIG5QlRjhugqRU9ZvvNlg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        meta.helm.sh/release-name: loki-stack
        meta.helm.sh/release-namespace: monitoring
    labels:
        app: prometheus
        app.kubernetes.io/managed-by: Helm
        component: alertmanager
        helm.toolkit.fluxcd.io/name: loki-stack
        helm.toolkit.fluxcd.io/namespace: monitoring
        heritage: Helm
        release: loki-stack
    name: loki-stack-prometheus-alertmanager
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9z8z69fa63fa8pnxklq00e8k3556sc233wlp20na7cykthtgvgqwnvej5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWXhYMkQ5SFZndDEzK01M
            SlJIY3ZvcTdUNlNJMStsUldPeSswSGxzVDFFCi8wbkdEMXhjNVZaS0lSclliN29r
            MWx1dFFSYk13R2plYTVFZWtvZmtCdmMKLS0tIHlMRlFZMzBJTFFXNE1KdHBmclhu
            K3FVRXR2VWlFa2Q0bzFwbWJ1Ukl5SE0KWYbRYaI4NxBgx2zkSWC1KxrTYDnTN3aT
            amf4oaZK87UsXwCclGyQBI5NXQTs0iXuo/HCHyhMpSEatHV3o7v0LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T08:42:11Z"
    mac: ENC[AES256_GCM,data:QOuJTPfW7t6q5dEoU4uqIxvAFYxbNbz6D350Ya4/7DgyKo8cFRDCdOwjsh9GXr+CcdzRQWKXldSHiTKuj4N3urhuLswOAFwX/yEZ2lDasi2gXJi7DzvDkjfNBfeaPb0ZAq1EUoPRJPChfzE7sQoJfDonbQ61NAx1HtfNWWEb2B0=,iv:0LtGnsFMY1tgaMOW8m3oiUZtRnUjqRqsQKLcD3V6W34=,tag:fvVczB8g0TihgLj8NccFUg==,type:str]
    pgp: []
    encrypted_regex: ^(alertmanager.yml)$
    version: 3.8.1
