apiVersion: v1
data:
    alertmanager.yml: ENC[AES256_GCM,data:Zfan2DWJ20pFt5u1DyTLsf+srhoT4NrPUcNAs7v0IaDSliTiq/AoUxoGMKVw4uxIitnjf5enIz+E5qUMVsmIPEiXP8bc8N5Vi6xaPFynRN73+NfNvqpLWleYqQYFzQGY7a5FVtoIirPrvAylr9/OmIbMX3AbDMADU83CwRbYGGP/PZtmM0DgWL1/ZOd0t/ceOiVi9gW5chR2uyYE9NL/z6/eFZXEzVOg9hRiPA0sH2jTB8WkLSmWtqbQCvBbjFMnywDwn2wHexW4ru31B9vvdhUn4MHvlyWuBiEUNbCgO2UU0FjU5D2XYTaj2kNDYWQpO8EhkKBXJ0p7uKCXF22SiimDrTJw/ZveG5qgggX7DihRdmUZ8HdWc0ihwKEy7pnvoijpk7AG7SxRVsk6YZkQU9SXHN/hA7RaiYkWbvmiIl0Fn85K8Bm4cXKYwJpejN+XZu9wd3ScS1XHufNyDX0s0DyR+budNO8TlLw+3zxBFgIvGX2t2uvgSdpD/ph7xSCCWglVshJAEVVxBPyOWxFjZ0/Q/LWQ+PBF2i/PkmKPiP1RlgRL4KUdEOyXhD49AhpdgBMKuN6FIOuCzsgpBASArAIDRtMwDVOAd4sxqly8CVGpzpnx9Pr1pVKUcKaU4mgyooZCEDKeNVio5Bt70dBN+BMFnNawiUfn33rWyn36/a3Hnvv2DqH8xS+NVqz9q+E5o8abVh5RioVfdZxC1KeZYzYACN+KqeGu5ZZNaC1Tx6hVWKW7O+hI3eESXvQIrFRI2S1you1sH5XbVafQ0s30LSpy+9HRqM6Oqm1RCLrpOSUcz6VAKJHCv23yjLlapNFIFHm4eGfJf1hfxevV2hWNq7xICmaB8rmfv2QdVh1bqukgXvxtjocPdUZ8t/4aV3vdwhJTX9QjD319O5HizreXY0IodI1lEH7O5h9fcbqDubW+cvv0l2i9w9dyv7ixBg6Opk3DGT34Jp5cfpWeNh6kHfDKnb1bdPpoVZSPzEM=,iv:VfPsBkiN7+W6zLrQZkhLoxeInfuHAbw/BWb+8uKlgfM=,tag:jmwp/bPpjuyIyEPH5rmmyw==,type:str]
kind: ConfigMap
metadata:
    annotations:
        meta.helm.sh/release-name: loki-stack
        meta.helm.sh/release-namespace: monitoring
    labels:
        app: prometheus
        app.kubernetes.io/managed-by: Helm
        component: alertmanager
        helm.toolkit.fluxcd.io/name: loki-stack
        helm.toolkit.fluxcd.io/namespace: monitoring
        heritage: Helm
        release: loki-stack
    name: loki-stack-prometheus-alertmanager
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9z8z69fa63fa8pnxklq00e8k3556sc233wlp20na7cykthtgvgqwnvej5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbzNSemlwdmxGTm9CUHo1
            Q2hnYWdJOTBaVGpoWFFXNmdrbFdGZnd0VW5VCkcybzdpa2VxNjJBdXhQWTYrVU1J
            Z1pPK2ZBKzAxZ09NSTNUMzU3VnVYQXMKLS0tIERFTDVlMG9RM2pOakVKeGR0MFNj
            T2ZzeUd4QmdibEhCbTV1Wk1iaDN0VDAKBRB5xh9Qp70RafiGCD6ciR6AQvVQAJ6M
            BFzVI+SPyk9EzMa9JIOfcEJICwy/pwzs3FehMr/MQ906yG3XlOqWSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ysm820ajay8wqslnkjqcewvq4tmeucth3a88qk4a7hl0mnwkfaqmj6xx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU0VSbG9jVWdkTElkYnhz
            YTdnK3RjRlFsWFNyYlZ5NUIybUtiMDBVSkVRClZwUkM3V1lZVmRsVS9zMStLazJW
            aTlkWmRTMllDUUxmZWRYeXpqZXZtTVkKLS0tIHdkTUd6eGRMcmV5ei9Mck1ncUF4
            M2Zud3Bxc0hCV2lNZUhNNjJqYW5vRkkKUIWWqzcgY6mD807nendl5oF7HiyOyITR
            HsNNQX3m3FKBtRS6zoia6o3wryLv707lmbjkz24MS4xbJLzp+YnUqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T08:36:37Z"
    mac: ENC[AES256_GCM,data:Krl0TxvJv3dT6CwaHA0pOSK6yyIZ3rApCohXCk6G4mbEWPTh1POaaZEM0xXxrqW256KfafdZVj3uLAOWLSGUYd3dlNTzQU9iwIq4VHJ7OSPBpl3fJno2r4jyGMeqRT4fZdvlh/BjaNEt5mFoymC9hZBbxS2LqpJ0TLp4yztVf9w=,iv:uD7G5N/ZSH0dq/CfmWFzWuOre3aO9JuvTvffvWSu5l4=,tag:ytiv6Z2cM0GhSp/ZWMluHg==,type:str]
    pgp: []
    encrypted_regex: ^(alertmanager.yml)$
    version: 3.8.1
