apiVersion: v1
data:
    alertmanager.yml: ENC[AES256_GCM,data:PUQ/aV8FtXCHZ3qp4jywgQIL8vSYHPaRmROt+BQgeVDYD/exEUQlZlCGHNJbIYiiFxhFzBMMsFPj6Sc6E516jB+Uovkq7kNbwrdwWIDNcNnLCfcG/aOhLKsTbakuRMlX2y963IhneJSu0VWansoX2uZypyYERJJSeFYe/OYHMIVP2ywJg1G6aZTmKWIlr5DPfjDOhtkZ1umTBBrdpQFSLo0+ft7VK1CMU48hp8LYwv0ECSjhJZ3GHJo4Dbddn6ohXNjni4t+dTAv6KwCoRuplRlbkb1CJmhPLHWDKt8c4LIhS1DpPKA1H+AoGlwiM5wOgL7FUmBlhPyyvMU5ZZIhvtgQ306ynw0INsEIHlzwlQ1LRzL7H2Co71Ow6XfmJiq1RNUu/s6977IkTA4zOrxTPE8OBL5GXU2wPQfqqbFnqVH2OaRTFq2aCdrXGiLn+DccSUKkd0RCvreWkSEKZP0azPLkLPrlB6i8Qu+ebJRIGGij+Cxp1ZAys/YqVWRuacwMMWzXVUBB1G4wP7TZlhXCUie0L/pPo+vnDMKDRpLExl6asfTfYJ7KXG7SJ8zkrzccS9ryMCttINr+9Eo7vAT44s6yK+thEEUD8rt3pRDveYQQvaQ6z0fHw1lTl2IV0X4GCnRTkJMZe6Kl6ATKH5hUZYCBsgu5hNFIvBv9PynuGGQtjE7wPziHoICTl5Jnc5DsMHVIceI09QgoVgGQ2UP4md18jkivc5HEbq7mfPAwSsbf3p8LpDdAttKPOXXU4MgwpzlyohgmdEY=,iv:jto1IYyN9rI2B22RV5UdKjsZQ5p8aItej+nRydTr2H0=,tag:mfvI1DCrTc0GLzMoeuuEHg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        meta.helm.sh/release-name: loki-stack
        meta.helm.sh/release-namespace: monitoring
    labels:
        app: prometheus
        app.kubernetes.io/managed-by: Helm
        component: alertmanager
        helm.toolkit.fluxcd.io/name: loki-stack
        helm.toolkit.fluxcd.io/namespace: monitoring
        heritage: Helm
        release: loki-stack
    name: loki-stack-prometheus-alertmanager
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9z8z69fa63fa8pnxklq00e8k3556sc233wlp20na7cykthtgvgqwnvej5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeW9vOWRoK3RnZVcyZFBm
            OVB3cVAwTUNaWlhuaXUyampLODIvcTRpYWlBCnA2dHo3Q0JWaDh0SFkrTldjYVpN
            UWdkVFF5VU1mcEZoQndhcUtUN0FMazQKLS0tIEZiaEc1YVp2R1h4czZvN3Viei9M
            YkNQMzljUlBUdzdwSXRORU13U0c2Z28KxAbgF7c4XuSQlJl0JDB1VYtTI4ejqq64
            Pm2d6hsjAbQqM1neSwLxuhut4P1yOoN9FKVEB+fAUc9qHP4We28v8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T20:26:34Z"
    mac: ENC[AES256_GCM,data:HHVkfmfiGqsqzguGUQV04R/kDFPKjqLippEM1NCicRnN7niyBwQMePvKzOyVza7TGYhd47EyRW7Jh3ZhyV0rQ6mkU9C7wnGkP8xK65BnM1Ycr38XcSKD2HnkWkoKWLYdrFvSpJtnXu1CKbJ8R9moCyzIrUeTDyTX6J8/f5KnCbQ=,iv:J6VXgpmYi3MlKgoOe2sjAonhpSZT/wJdtt0koDaXM7k=,tag:axyk3BmhQINZqKsY6/x/PQ==,type:str]
    pgp: []
    encrypted_regex: ^(alertmanager.yml)$
    version: 3.8.1
