apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: komga
    targetRevision: 0.0.6
    helm:
      values: |
        common:
          ingress:
            enabled: true
            hostName: "komga.<path:kv/cloudflared#domain>"
            ingressClassName: traefik
            tls:
              enabled: true
              secretName: "komga-tls"
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
