apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-spotify
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: your-spotify
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: your-spotify
    targetRevision: 0.0.1
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            web:
              name: "web"
              variables:
                nonSecret:
                  API_ENDPOINT: https://spotty-api.<path:kv/cluster#domain>
              ingress:
                enabled: true
                hostName: spotty.<path:kv/cluster#domain>
                ingressClassName: "traefik"
                extraLabels: {}
                tls:
                  enabled: true
                  secretName: spotty
                annotations:
                  cert-manager.io/cluster-issuer: cloudflare

            server:
              variables:
                secret:
                  data:
                    SPOTIFY_PUBLIC: <path:kv/spotify#access>
                    SPOTIFY_SECRET: <path:kv/spotify#private>
                nonSecret:
                  API_ENDPOINT: https://spotty-api.<path:kv/cluster#domain>
                  CLIENT_ENDPOINT: https://spotty.<path:kv/cluster#domain>
                  MONGO_ENDPOINT: mongodb://your-spotify-mongodb:27017/your_spotify
              ingress:
                enabled: true
                ingressClassName: "traefik"
                hostName: spotty-api.<path:kv/cluster#domain>
                extraLabels: {}
                tls:
                  enabled: true
                  secretName: spotty-api
                annotations:
                  cert-manager.io/cluster-issuer: cloudflare
