apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.15
    helm:
      values: |
        annotations:
          reloader.stakater.com/auto: "true"
        admin:
          existingSecret: grafana-secrets
          userKey: admin-user
          passwordKey: admin-password
        envValueFrom:
          CH_PASSWORD:
            secretKeyRef:
              name: grafana-secrets
              key: CH_PASSWORD
          OIDC_CLIENT_ID:
            secretKeyRef:
              name: grafana-secrets
              key: OIDC_CLIENT_ID
          OIDC_CLIENT_SECRET:
            secretKeyRef:
              name: grafana-secrets
              key: OIDC_CLIENT_SECRET
        plugins:
          - chaosmeshorg-datasource
          - grafana-clickhouse-datasource
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: SigNoz ClickHouse
                uid: signoz-clickhouse
                type: grafana-clickhouse-datasource
                access: proxy
                jsonData:
                  host: signoz-clickhouse.signoz.svc.cluster.local
                  port: 9000
                  protocol: native
                  secure: false
                  username: admin
                secureJsonData:
                  password: $__env{CH_PASSWORD}
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
          hosts:
            - "grafana.mocha.thoughtless.eu"
          tls:
            - secretName: grafana-tls
              hosts:
                - "grafana.mocha.thoughtless.eu"
        persistence:
          type: pvc
          enabled: true
        deploymentStrategy:
          type: Recreate
        assertNoLeakedSecrets: false
        grafana.ini:
            server:
              root_url: https://grafana.mocha.thoughtless.eu
            auth:
                signout_redirect_url: "https://authentik.mocha.thoughtless.eu/application/o/grafana/end-session/"
                oauth_auto_login: false
            auth.generic_oauth:
                name: authentik
                enabled: true
                client_id: $__env{OIDC_CLIENT_ID}
                client_secret: $__env{OIDC_CLIENT_SECRET}
                scopes: "openid profile email"
                auth_url: "https://authentik.mocha.thoughtless.eu/application/o/authorize/"
                token_url: "https://authentik.mocha.thoughtless.eu/application/o/token/"
                api_url: "https://authentik.mocha.thoughtless.eu/application/o/userinfo/"
                allow_assign_grafana_admin: true
                role_attribute_path: "contains(groups[*], 'authentik Admins') && 'GrafanaAdmin' || 'Viewer'"
        sidecar:
          datasources:
            enabled: true
          dashboards:
            enabled: true
        serviceMonitor:
          enabled: false
        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: grafana-secrets
            spec:
              refreshInterval: "1h"
              secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
              target:
                name: grafana-secrets
                creationPolicy: Owner
              data:
                - secretKey: admin-user
                  remoteRef:
                    key: grafana
                    property: user
                - secretKey: admin-password
                  remoteRef:
                    key: grafana
                    property: pass
                - secretKey: CH_PASSWORD
                  remoteRef:
                    key: signoz-clickhouse
                    property: password
                - secretKey: OIDC_CLIENT_ID
                  remoteRef:
                    key: grafana
                    property: authentik_id
                - secretKey: OIDC_CLIENT_SECRET
                  remoteRef:
                    key: grafana
                    property: authentik_secret
