apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 74.2.1
    helm:
      values: |
        defaultRules:
          create: true
          rules:
            kubeProxy: false
            kubeControllerManager: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        prometheusOperator:
          admissionWebhooks:
            certManager:
              enabled: true
        prometheus:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
              traefik.ingress.kubernetes.io/router.middlewares: monitoring-basic-auth-prometheus@kubernetescrd
            hosts:
              - prometheus.<path:kv/cluster#domain>
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.<path:kv/cluster#domain>
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            enableRemoteWriteReceiver: true
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 30Gi
        crds:
          enabled: true
        grafana:
          enabled: false
