---
- hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Create directory
    file:
      path: "/home/{{ utilisateur }}/.ssh/"
      state: directory
      owner: "{{ utilisateur }}"
      group: "{{ utilisateur }}"
      
  - name: Create authorized_keys for the default user if not exists
    copy:
      dest: "/home/{{ utilisateur }}/.ssh/authorized_keys"
      content: ""
      owner: "{{ utilisateur }}"
      group: "{{ utilisateur }}"
      force: no

  - name: Create authorized_keys for the default user if not exists
    copy:
      dest: "/home/{{ utilisateur }}/.ssh/authorized_keys"
      content: ""
      owner: "{{ utilisateur }}"
      group: "{{ utilisateur }}"
      force: no

  - name: "Install packages"
    apt:
      name: "{{item}}"
      state: present
    loop:
      - vim
      - exa
      - grc
      - most
      - highlight
      - source-highlight
      - python3-pygments
      - gawk
      - git
      - gnupg
      - net-tools
      - dnsutils
      - python3-apt
      - qemu-guest-agent

  - name: sudo without password for default user group
    copy:
      content: '{{ utilisateur }} ALL=(ALL:ALL) NOPASSWD:ALL'
      dest: /etc/sudoers.d/utilisateur
      mode: 0440