---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: ">=1.0.4"
      sourceRef:
        kind: HelmRepository
        name: rubxkube-charts
        namespace: flux-system
  values:
    common:

