apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system 
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: ">=v1.13.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  values:
    installCRDs: true
    prometheus:
      enabled: true
