apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: tang
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: matomo
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: toutou
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: tranquil-pds
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: abcdesktop
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: kamaji
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: rmfakecloud
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: thelounge
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: spindle
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: trmnl-server
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: netbird
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: blueweave
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: factorio-lucca
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: signoz
  annotations:
    volsync.backube/privileged-movers: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Prune=false
