apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  sourcePVC: vaultwarden-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-vaultwarden-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tang-data
  namespace: tang
spec:
  sourcePVC: tang-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-tang-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-vault-0
  namespace: vault
spec:
  sourcePVC: data-vault-0
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-vault-0
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-vault-1
  namespace: vault
spec:
  sourcePVC: data-vault-1
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-vault-1
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-vault-2
  namespace: vault
spec:
  sourcePVC: data-vault-2
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-vault-2
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-matomo-db-0
  namespace: matomo
spec:
  sourcePVC: data-matomo-db-0
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-matomo-db-0
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-toutou-db-0
  namespace: toutou
spec:
  sourcePVC: data-toutou-db-0
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-toutou-db-0
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-tranquil-pds-db-0
  namespace: tranquil-pds
spec:
  sourcePVC: data-tranquil-pds-db-0
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-tranquil-pds-db-0
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mongodb-data
  namespace: abcdesktop
spec:
  sourcePVC: mongodb-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-mongodb-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-kamaji-etcd-0
  namespace: kamaji
spec:
  sourcePVC: data-kamaji-etcd-0
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-kamaji-etcd-0
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-kamaji-etcd-1
  namespace: kamaji
spec:
  sourcePVC: data-kamaji-etcd-1
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-kamaji-etcd-1
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-kamaji-etcd-2
  namespace: kamaji
spec:
  sourcePVC: data-kamaji-etcd-2
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-data-kamaji-etcd-2
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: rmfakecloud-data
  namespace: rmfakecloud
spec:
  sourcePVC: rmfakecloud-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-rmfakecloud-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: grafana
  namespace: monitoring
spec:
  sourcePVC: grafana
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-grafana
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: thelounge-data
  namespace: thelounge
spec:
  sourcePVC: thelounge-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-thelounge-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: spindle-data
  namespace: spindle
spec:
  sourcePVC: spindle-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-spindle-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tranquil-pds-blobs
  namespace: tranquil-pds
spec:
  sourcePVC: tranquil-pds-blobs
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-tranquil-pds-blobs
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: matomo-data
  namespace: matomo
spec:
  sourcePVC: matomo-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-matomo-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: trmnl-server-data
  namespace: trmnl-server
spec:
  sourcePVC: trmnl-server-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-trmnl-server-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: netbird-management
  namespace: netbird
spec:
  sourcePVC: netbird-management
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-netbird-management
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: blueweave-data
  namespace: blueweave
spec:
  sourcePVC: blueweave-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-blueweave-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: authentik-github-une-pause-cafe-fr
  namespace: abcdesktop
spec:
  sourcePVC: authentik-github-une-pause-cafe-fr
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-authentik-github-une-pause-cafe-fr
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: factorio-data
  namespace: factorio-lucca
spec:
  sourcePVC: factorio-data
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-factorio-data
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: signoz-db-signoz-0
  namespace: signoz
spec:
  sourcePVC: signoz-db-signoz-0
  trigger:
    manual: paused-vg-full
  restic:
    repository: restic-signoz-db-signoz-0
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvmpv-snapshot
    cacheCapacity: 512Mi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
