apiVersion: v1
kind: Secret
metadata:
  name: bank-vaults-helm-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bank-vaults
  type: helm
  url: ghcr.io/bank-vaults/helm-charts
  enableOCI: "true"
