apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-vaults-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: ghcr.io/bank-vaults/helm-charts
    chart: vault-secrets-webhook
    targetRevision: 1.23.1
    helm:
      values: |
        replicaCount: 2
        env:
          VAULT_ADDR_ALLOWLIST: "https://vault.bank-vaults:8200,https://vault.bank-vaults.svc:8200,https://vault.bank-vaults.svc.cluster.local:8200"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: bank-vaults
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
