apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/common-charts/
    chart: common
    targetRevision: v0.4.2
    helm:
      values: |
        name: "slash"
        image:
          repository: yourselfhosted/slash
          tag: "1.0.0"
        deployment:
          port: 5231
        service:
          containerPort: 5231
        ingress:
            enabled: true
            hostName: "slash.<path:kv/cluster#domain>"
            ingressClassName: traefik
            tls:
              enabled: true
              secretName: "slash-tls"
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
              external-dns.alpha.kubernetes.io/hostname: "slash.<path:kv/cluster#domain>"
              external-dns.alpha.kubernetes.io/target: "<path:kv/cloudflare#tunnelid>.cfargotunnel.com"
        variables:
          secret: {}
          nonSecret:
            SLASH_PORT: "5231"
        persistence:
          enabled: true
          volumes:
            - name: data
              storageClassName: ""
              size: 5Gi
              pvcClaim: ""
              containerMount: "/var/opt/slash"
  destination:
    server: https://kubernetes.default.svc
    namespace: slash
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
