apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/common-charts/
    chart: common
    targetRevision: v0.4.2
    helm:
      values: |
        name: "slash"
        image:
          repository: yourselfhosted/slash
          tag: "1.0.0"
        deployment:
          port: 5231
        service:
          containerPort: 5231
        persistence:
          enabled: true
          volumes:
            - name: data
              storageClassName: ""
              size: 5Gi
              pvcClaim: ""
              containerMount: "/var/opt/slash"
  destination:
    server: https://kubernetes.default.svc
    namespace: slash
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
