---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: qjoly
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/qjoly/GitOps
  ref:
    branch: main

