---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 15m
  chart:
    spec:
      chart: vault
      version: ">=v0.27.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    injector:
      enabled: false
    csi:
      enabled: true


