apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spegel-org/spegel
    chart: spegel
    targetRevision: v0.0.30
    path: charts/spegel
    helm:
      releaseName: spegel
  destination:
    server: https://kubernetes.default.svc
    namespace: spegel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
