apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spegel-org/spegel
    targetRevision: v0.3.0
    path: charts/spegel
    helm:
      releaseName: spegel
      values: |
        spegel:
          containerdRegistryConfigPath: /etc/cri/conf.d/hosts
        image: 
          tag: v0.3.0
  destination:
    server: https://kubernetes.default.svc
    namespace: spegel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
