apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/spegel-org/spegel
    targetRevision: v0.7.3
    path: charts/spegel
    helm:
      releaseName: spegel
      values: |
        spegel:
          containerdRegistryConfigPath: /etc/cri/conf.d/hosts
        image:
          tag: v0.6.0
  destination:
    server: https://kubernetes.default.svc
    namespace: spegel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
