apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: audiobookshelf
    targetRevision: v0.0.2
    helm:
      values: |
        common:
          ingress:
              enabled: true
              hostName: "audiobookshelf.<path:kv/cluster#domain>"
              ingressClassName: traefik
              tls:
                enabled: true
                secretName: "audiobookshelf-tls"
              annotations:
                cert-manager.io/cluster-issuer: cloudflare
          variables:
            secret: {}
            nonSecret: 
              TZ: "Europe/Paris"
  destination:
    server: https://kubernetes.default.svc
    namespace: audiobookshelf
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
