site_name: GitOps
site_description: My full homelab setup based on Packer/Terraform/Kubernetes
site_author: Quentin JOLY
repo_name: qjoly/GitOps
repo_url: https://github.com/qjoly/GitOps
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button
edit_uri: "edit/main/docs/src/"

# Configuration
theme:
  name: material

  # Static files
#  static_templates:
#    - 404.html

  # logo: https://raspbernetes.github.io/img/logo.svg
  # favicon: https://raspbernetes.github.io/img/logo.svg
  language: fr

  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    - navigation.sections
    - content.code.annotate

docs_dir: ../docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qjoly
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/quentin-joly-it/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheBidouilleur
    - icon: fontawesome/solid/paper-plane
      link: mailto:quentin@thebidouilleur.xyz
    - icon: fontawesome/brands/medium
      link: https://thebidouilleur.xyz
copyright: Copyright &copy; 2023 TheBidouilleur


plugins:
  - search
  - git-revision-date-localized
  - autolinks
  - diagrams
  - glightbox


markdown_extensions:
  - admonition
  - abbr
  - meta
  - md_in_html
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Introduction: index.md
  - General:
      - Installer les dépendances: dep.md
      - Lancement du projet: start.md
  - Hyperviseurs:
      - Configurer Libvirt: libvirt.md
      - Configurer Proxmox: proxmox.md
  - Autre:
      - Chiffrer vos secrets: sops.md