apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: glance
    targetRevision: 0.0.8
    helm:
      values: |
        common:
          ingress:
            enabled: true
            hostName: "glance.<path:kv/cluster#domain>"
            ingressClassName: traefik
            tls:
              enabled: true
              secretName: "glance-tls"
            annotations:
              cert-manager.io/cluster-issuer: cloudflare

          configMap:
            enabled: true
            data:
              - name: "config"
                mountPath: "/mnt"
                data:
                  - content:
                      glance.yml: |
                        pages:
                          - name: Home
                            columns:
                              - size: small
                                widgets:
                                  - type: calendar

                                  - type: rss
                                    limit: 20
                                    collapse-after: 5
                                    cache: 3h
                                    feeds:
                                      - url: https://justingarrison.com/index.xml
                                      - url: https://blog.zwindler.fr/index.xml
                                      - url: https://samwho.dev/rss.xml
                                      - url: https://blog.stonegarden.dev/index.xml
                                      - url: http://blog.garambrogne.net/feeds/all.rss
                                      - url: https://blog.wescale.fr/rss.xml
                                      - url: https://fredix.xyz/index.xml
                                      - url: https://blog.cetinich.net/blog/atom.xml
                                      - url: https://littlejo.github.io/blog/index.xml
                                      - url: https://www.itix.fr/fr/index.xml
                                      - url: https://mickael-baron.fr/feed.xml
                                      - url: https://blog.claneys.net/rss/
                                      - url: https://www.rootisgod.com/index.xml
                                      - url: https://www.joshkasuboski.com/index.xml
                                      - url: https://blog.paranoidpenguin.net/index.xml
                                      - url: https://newsletter.developer-friendly.blog/archive.xml
                                      - url: https://xn--gckvb8fzb.com/index.xml
                                      - url: http://sreweekly.com/feed/
                                      - url: https://dustri.org/b/rss.xml
                                      - url: https://blog.squwal.com/index.xml
                                      - url: https://alexohneander.de/atom.xml
                                      - url: https://flagzeta.org/til/index.xml
                                      - url: https://blog.scottlowe.org/feed.xml
                                      - url: https://makhal.fr/index.xml
                                      - url: https://danmanners.com/index.xml
                                      - url: https://blog.tbobm.dev/index.xml
                                      - url: https://searchmysite.net/api/v1/feed/search/?q=Talos
                                      - url: https://xeiaso.net/blog.rss

                                  - type: twitch-channels
                                    channels:
                                      - cuistops
                                      - therealseboss666
                                      - yorzian

                              - size: full
                                widgets:
                                  - type: search
                                    search-engine: duckduckgo
                                    bangs:
                                      - title: YouTube
                                        shortcut: "!yt"
                                        url: https://www.youtube.com/results?search_query={QUERY}
                                      - title: Github
                                        shortcut: "!git"
                                        url: https://github.com/search?q={QUERY}
                                      - title: Lucca
                                        shortcut: "!lucca"
                                        url: https://github.com/LuccaSA/?q={QUERY}
                                  - type: hacker-news

                                  - type: videos
                                    channels:
                                      - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                                      - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                                      - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

                              - size: small
                                widgets:
                                  - type: weather
                                    location: Lyon, France

                                  - type: releases
                                    show-source-icon: true
                                    repositories:
                                      - siderolabs/talos
                                      - siderolabs/omni
                                      - cilium/cilium
                                      - kubernetes/kubernetes
                                      - dockerhub:gotify/server
                          - name: RSS
                            columns:
                              - size: full
                                widgets:
                                
                                  - type: rss
                                    limit: 40
                                    collapse-after: 20
                                    cache: 3h
                                    feeds:
                                      - url: https://justingarrison.com/index.xml
                                      - url: https://blog.zwindler.fr/index.xml
                                      - url: https://samwho.dev/rss.xml
                                      - url: https://blog.stonegarden.dev/index.xml
                                      - url: http://blog.garambrogne.net/feeds/all.rss
                                      - url: https://blog.wescale.fr/rss.xml
                                      - url: https://fredix.xyz/index.xml
                                      - url: https://blog.cetinich.net/blog/atom.xml
                                      - url: https://littlejo.github.io/blog/index.xml
                                      - url: https://www.itix.fr/fr/index.xml
                                      - url: https://mickael-baron.fr/feed.xml
                                      - url: https://blog.claneys.net/rss/
                                      - url: https://www.rootisgod.com/index.xml
                                      - url: https://www.joshkasuboski.com/index.xml
                                      - url: https://blog.paranoidpenguin.net/index.xml
                                      - url: https://newsletter.developer-friendly.blog/archive.xml

