apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: glance
    targetRevision: 0.0.10
    helm:
      values: |
        common:
          ingress:
            enabled: true
            hostName: "glance.<path:kv/cluster#domain>"
            ingressClassName: traefik
            tls:
              enabled: true
              secretName: "glance-tls"
            annotations:
              cert-manager.io/cluster-issuer: cloudflare

          configMap:
            enabled: true
            data:
              - name: "config"
                mountPath: "/mnt"
                data:
                  - content:
                      glance.yml: |
                        pages:
                          - name: Home
                            columns:
                              - size: small
                                widgets:
                                  - type: calendar

                                  - type: rss
                                    limit: 20
                                    collapse-after: 5
                                    cache: 3h
                                    feeds:
                                      - url: https://justingarrison.com/index.xml
                                      - url: https://blog.zwindler.fr/index.xml
                                      - url: https://samwho.dev/rss.xml
                                      - url: https://blog.stonegarden.dev/index.xml
                                      - url: http://blog.garambrogne.net/feeds/all.rss
                                      - url: https://blog.wescale.fr/rss.xml
                                      - url: https://fredix.xyz/index.xml
                                      - url: https://blog.cetinich.net/blog/atom.xml
                                      - url: https://littlejo.github.io/blog/index.xml
                                      - url: https://www.itix.fr/fr/index.xml
                                      - url: https://mickael-baron.fr/feed.xml
                                      # - url: https://blog.claneys.net/rss/
                                      - url: https://www.rootisgod.com/index.xml
                                      - url: https://www.joshkasuboski.com/index.xml
                                      - url: https://blog.paranoidpenguin.net/index.xml
                                      # - url: https://newsletter.developer-friendly.blog/archive.xml
                                      - url: https://xn--gckvb8fzb.com/index.xml
                                      - url: http://sreweekly.com/feed/
                                      - url: https://dustri.org/b/rss.xml
                                      - url: https://blog.squwal.com/index.xml
                                      - url: https://alexohneander.de/atom.xml
                                      - url: https://flagzeta.org/til/index.xml
                                      - url: https://blog.scottlowe.org/feed.xml
                                      # - url: https://makhal.fr/index.xml
                                      - url: https://danmanners.com/index.xml
                                      - url: https://blog.tbobm.dev/index.xml
                                      - url: https://searchmysite.net/api/v1/feed/search/?q=Talos
                                      - url: https://xeiaso.net/blog.rss
                                      - url: https://perrotta.dev/index.xml
                                      - url: https://fasterthanli.me/index.xml
                                      - url: https://leofvo.me/articles/rss.xml
                                      - url: https://zoriya.dev/index.xml
                                      - url: https://mcorbin.fr/feed.xml
                                      - url: https://arthi-chaud.github.io/feed.xml
                                      - url: https://ersei.net/en/blog.atom


                                  - type: twitch-channels
                                    channels:
                                      - cuistops
                                      - therealseboss666
                                      - yorzian
                                      - thelaluka

                              - size: full
                                widgets:
                                  - type: search
                                    search-engine: duckduckgo
                                    bangs:
                                      - title: YouTube
                                        shortcut: "!yt"
                                        url: https://www.youtube.com/results?search_query={QUERY}
                                      - title: Github
                                        shortcut: "!git"
                                        url: https://github.com/search?q={QUERY}
                                      - title: Lucca
                                        shortcut: "!lucca"
                                        url: https://github.com/LuccaSA/?q={QUERY}
                                  - type: hacker-news

                                  - type: videos
                                    channels:
                                      - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                                      - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                                      - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

                              - size: small
                                widgets:
                                  - type: weather
                                    location: Nantes, France

                                  - type: releases
                                    show-source-icon: true
                                    repositories:
                                      - siderolabs/talos
                                      - siderolabs/omni
                                      - cilium/cilium
                                      - kubernetes/kubernetes
                          - name: RSS
                            columns:
                              - size: full
                                widgets:
                                
                                  - type: rss
                                    limit: 40
                                    collapse-after: 20
                                    cache: 3h
                                    feeds:
                                      - url: https://justingarrison.com/index.xml
                                      - url: https://blog.zwindler.fr/index.xml
                                      - url: https://samwho.dev/rss.xml
                                      - url: https://blog.stonegarden.dev/index.xml
                                      - url: http://blog.garambrogne.net/feeds/all.rss
                                      - url: https://blog.wescale.fr/rss.xml
                                      - url: https://fredix.xyz/index.xml
                                      - url: https://blog.cetinich.net/blog/atom.xml
                                      - url: https://littlejo.github.io/blog/index.xml
                                      - url: https://www.itix.fr/fr/index.xml
                                      - url: https://mickael-baron.fr/feed.xml
                                      # - url: https://blog.claneys.net/rss/
                                      - url: https://www.rootisgod.com/index.xml
                                      - url: https://www.joshkasuboski.com/index.xml
                                      - url: https://blog.paranoidpenguin.net/index.xml
                                      # - url: https://newsletter.developer-friendly.blog/archive.xml
                                      - url: https://xn--gckvb8fzb.com/index.xml
                                      - url: http://sreweekly.com/feed/
                                      - url: https://dustri.org/b/rss.xml
                                      - url: https://blog.squwal.com/index.xml
                                      - url: https://alexohneander.de/atom.xml
                                      - url: https://flagzeta.org/til/index.xml
                                      - url: https://blog.scottlowe.org/feed.xml
                                      # - url: https://makhal.fr/index.xml
                                      - url: https://danmanners.com/index.xml
                                      - url: https://blog.tbobm.dev/index.xml
                                      - url: https://searchmysite.net/api/v1/feed/search/?q=Talos
                                      - url: https://xeiaso.net/blog.rss
                                      - url: https://perrotta.dev/index.xml
                                      - url: https://fasterthanli.me/index.xml
                                      - url: https://leofvo.me/articles/rss.xml
                                      - url: https://zoriya.dev/index.xml
                                      - url: https://mcorbin.fr/feed.xml
                                      - url: https://arthi-chaud.github.io/feed.xml
                                      - url: https://ersei.net/en/blog.atom
                          - name: RSS
                            columns:
                              - size: small
                                widgets:
                                  - type: custom-api
                                    hide-header: true
                                    title: Should I deploy today
                                    cache: 1h
                                    url: https://shouldideploy.today/api?tz=Europe%2FParis
                                    method: GET
                                    template: |
                                      <div class="deploy-card {{ if .JSON.Bool "shouldideploy" }}deploy-yes{{ else }}deploy-no{{ end }}">
                                        <style>
                                          .deploy-card {
                                            width: 100%;
                                            max-width: unset;
                                            margin: 0;
                                            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                                            transition: transform 0.2s ease, box-shadow 0.2s ease;
                                            border-radius: 12px;
                                            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
                                            padding: 24px 20px 18px 20px;
                                            text-align: left;
                                          }
                                          .deploy-card.deploy-yes {
                                            background: #9FC87E;
                                          }
                                          .deploy-card.deploy-no {
                                            background: #FF3F33;
                                          }
                                          .deploy-card h1 {
                                            font-size: 24px;
                                            margin: 0 0 16px;
                                            line-height: 1.3;
                                            color: #FFE6E1;
                                          }
                                          .deploy-message {
                                            font-size: 20px;
                                            font-weight: 600;
                                            margin: 12px 0 8px 0;
                                            color: #232634;
                                          }
                                          .deploy-date {
                                            font-size: 14px;
                                            color: #232634;
                                            margin-bottom: 4px;
                                          }
                                          .deploy-tz {
                                            font-size: 13px;
                                            color: #075B5E;
                                          }
                                          @media (max-width: 600px) {
                                            .deploy-card {
                                              padding: 16px;
                                            }
                                            .deploy-card h1 {
                                              font-size: 20px;
                                            }
                                            .deploy-message {
                                              font-size: 16px;
                                            }
                                          }
                                        </style>
                                        <h1>Should I deploy today?</h1>
                                        <div class="deploy-message">{{ .JSON.String "message" }}</div>
                                        <div class="deploy-tz">Timezone: {{ .JSON.String "timezone" }}</div>
                                      </div>
                                  - type: custom-api
                                    title: Slack Status
                                    cache: 1m
                                    url: https://slack-status.com/api/v2.0.0/current
                                    template: |
                                      <div class="flex items-center gap-15">
                                        <svg class="monitor-site-icon flat-icon" alt="Slack Logo" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M5.042 15.165a2.528 2.528 0 0 1-2.52 2.523A2.528 2.528 0 0 1 0 15.165a2.527 2.527 0 0 1 2.522-2.52h2.52v2.52zM6.313 15.165a2.527 2.527 0 0 1 2.521-2.52 2.527 2.527 0 0 1 2.521 2.52v6.313A2.528 2.528 0 0 1 8.834 24a2.528 2.528 0 0 1-2.521-2.522v-6.313zM8.834 5.042a2.528 2.528 0 0 1-2.521-2.52A2.528 2.528 0 0 1 8.834 0a2.528 2.528 0 0 1 2.521 2.522v2.52H8.834zM8.834 6.313a2.528 2.528 0 0 1 2.521 2.521 2.528 2.528 0 0 1-2.521 2.521H2.522A2.528 2.528 0 0 1 0 8.834a2.528 2.528 0 0 1 2.522-2.521h6.312zM18.956 8.834a2.528 2.528 0 0 1 2.522-2.521A2.528 2.528 0 0 1 24 8.834a2.528 2.528 0 0 1-2.522 2.521h-2.522V8.834zM17.688 8.834a2.528 2.528 0 0 1-2.523 2.521 2.527 2.527 0 0 1-2.52-2.521V2.522A2.527 2.527 0 0 1 15.165 0a2.528 2.528 0 0 1 2.523 2.522v6.312zM15.165 18.956a2.528 2.528 0 0 1 2.523 2.522A2.528 2.528 0 0 1 15.165 24a2.527 2.527 0 0 1-2.52-2.522v-2.522h2.52zM15.165 17.688a2.527 2.527 0 0 1-2.52-2.523 2.526 2.526 0 0 1 2.52-2.52h6.313A2.527 2.527 0 0 1 24 15.165a2.528 2.528 0 0 1-2.522 2.523h-6.313z"/></svg>
                                        <div class="grow min-width-0">
                                          <a class="size-h3 color-highlight text-truncate block" href="https://slack-status.com/" target="_blank" rel="noreferrer" title="Slack Status">Slack</a>
                                          <ul class="list-horizontal-text">
                                            {{ if eq (.JSON.String "status") "ok" }}
                                              <ul class="list-horizontal-text">
                                                <li>OK</li>
                                                <li title="Time since last outage" {{ .JSON.String "date_updated" | parseTime "rfc3339" | toRelativeTime }}></li>
                                              </ul>
                                            {{ else }}
                                              <ul class="list-horizontal-text">
                                                <li class="color-negative">OUTAGE</li>
                                                <li title="Time outage was last updated" {{ .JSON.String "date_updated" | parseTime "rfc3339" | toRelativeTime }}></li>
                                              </ul>
                                            {{ end }}
                                          </ul>
                                        </div>
                                  
                                        <div class="monitor-site-status-icon">
                                            {{ if eq (.JSON.String "status") "ok" }}
                                            <svg fill="var(--color-positive)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm3.857-9.809a.75.75 0 0 0-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 1 0-1.06 1.061l2.5 2.5a.75.75 0 0 0 1.137-.089l4-5.5Z" clip-rule="evenodd" />
                                            </svg>
                                            {{ else }}
                                            <svg fill="var(--color-negative)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495ZM10 5a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 10 5Zm0 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" clip-rule="evenodd"></path>
                                            </svg>
                                            {{ end }}
                                        </div>
                                      </div>
