apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz-operator
  source:
    repoURL: https://charts.signoz.io
    chart: signoz-operator
    targetRevision: 0.0.1
    helm:
      values: |
        crds:
          install: true
          keep: true
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
        rbac:
          namespaced: false
        controller:
          replicas: 1
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
