apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorio-lucca
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: factorio-lucca
  source:
    repoURL: https://rubxkube.github.io/common-charts/
    chart: common
    targetRevision: v0.6.0
    helm:
      values: |
              name: "factorio"
              service:
                type: NodePort
                enabled: true
                servicePort: 34197
                containerPort: 34197
                protocol: UDP
              
              deployment:
                port: 34197
                minReplicas: 0
              image:
                repository: factoriotools/factorio
                tag: "2.0"
                pullPolicy: Always
              
              ingress:
                enabled: false
              
              configMap:
                enabled: false
              
              extraConfigMaps: []
              
              variables:
                secret:
                  existingSecret:
                    - envName: USERNAME
                      name: factorio-secrets
                      key: username
                    - envName: TOKEN
                      name: factorio-secrets
                      key: token
                nonSecret:
                  DLC_SPACE_AGE: true
              extraResources:
                - apiVersion: external-secrets.io/v1
                  kind: ExternalSecret
                  metadata:
                    name: factorio-secrets
                  spec:
                    refreshInterval: "1h"
                    secretStoreRef:
                      name: vault-backend
                      kind: ClusterSecretStore
                    target:
                      name: factorio-secrets
                      creationPolicy: Owner
                    data:
                      - secretKey: username
                        remoteRef:
                          key: factorio
                          property: username
                      - secretKey: token
                        remoteRef:
                          key: factorio
                          property: token
              
              persistence:
                enabled: true
                volumes:
                  - name: data
                    storageClassName: ""
                    size: 20Gi
                    pvcClaim: ""
                    containerMount: "/factorio"
