apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  source:
    repoURL: https://rubxkube.github.io/common-charts/
    chart: common
    targetRevision: v0.4.3
    helm:
      values: |
        name: "freshrss"
        service:
          enabled: true
          servicePort: 80
          containerPort: 80

        image:
          repository: lscr.io/linuxserver/freshrss
          tag: 1.25.0
          
        deployment:
          port: 80
        variables:
          nonSecret: {}

        ingress:
          enabled: true
          hostName: "freshrss.<path:kv/cluster#domain>"
          ingressClassName: traefik
          tls:
             enabled: true
             secretName: "freshrss-tls"
          annotations:
             cert-manager.io/cluster-issuer: cloudflare

        configMap:
          enabled: false

        extraConfigMaps: []

        persistence:
          enabled: true
          volumes:
            - name: data
              storageClassName: ""
              size: 5Gi
              pvcClaim: ""
              containerMount: "/config"
