apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  source:
    repoURL: https://github.com/rubxkube/charts
    targetRevision: main
    path: charts/cloudflare-tunnel
    helm:
      values: |
        cloudflare:
          tunnelName: "turing-cluster"
          secretName: "cloudflare-tunnel-credentials"
          protocol: "http2"
          ingress:
            - hostname: "*.thoughtless.eu"
              service: "https://traefik.traefik.svc.cluster.local:443"
              originRequest:
                noTLSVerify: true

        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

        replicaCount: 1
