apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.bank-vaults:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
type: Opaque
data:
  credentials.json: dmF1bHQ6a3YvZGF0YS9jbG91ZGZsYXJlI2NyZWRlbnRpYWxz
