apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-credentials
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflare
        property: credentials
