apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  source:
    repoURL: https://charts.gabe565.com
    chart: adguard-home
    targetRevision: 0.3.25
    helm:
      values: |
        env:
          TZ: "Europe/Paris"
