apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-oidc
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: argocd
        property: client_secret
