apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.0
    helm:
      values: |
        server:
          affinity: ""
          ha:
            enabled: true
            raft:
              enabled: true
        injector:
          enabled: false
        csi:
          enabled: false
        ui:
          enabled: true
          serviceType: "ClusterIP"
          externalPort: 8200
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
