apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: kyoo
    targetRevision: 0.1.2
    helm:
      values: |
        volumes:
          media:
            enabled: false
        secrets:
          rabbitmq:
            enabled: false
          kyoo:
            enabled: false
        config:
          data:
            LIBRARY_LANGUAGES: "fr"
        extraResources:
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: kyoo-secrets
            spec:
              refreshInterval: "30s"
              secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
              target:
                name: kyoo-secrets
              data:
              - secretKey: kyoo-apikeys
                remoteRef:
                  key: kyoo
                  property: kyoo-apikeys
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: kyoo-rabbitmq
            spec:
              refreshInterval: "30s"
              secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
              target:
                name: kyoo-rabbitmq
              data:
              - secretKey: rabbitmq_user
                remoteRef:
                  key: kyoo
                  property: rabbitmq_user
              - secretKey: rabbitmq_password
                remoteRef:
                  key: kyoo
                  property: rabbitmq_password
              - secretKey: erlang_cookie
                remoteRef:
                  key: kyoo
                  property: erlang_cookie

  destination:
    server: https://kubernetes.default.svc
    namespace: kyoo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
