apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matomo
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: matomo-db
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
      jqPathExpressions:
        - '.spec.volumeClaimTemplates[].spec.volumeMode'
        - '.spec.volumeClaimTemplates[].status'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: matomo
  source:
    repoURL: https://github.com/qjoly/gitops.git
    targetRevision: HEAD
    path: mocha/apps/matomo/manifests
