apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-k8s-infra
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz-k8s-infra
  source:
    repoURL: https://charts.signoz.io
    chart: k8s-infra
    targetRevision: 0.16.0
    helm:
      values: |
        global:
          clusterName: turing
          deploymentEnvironment: production
        otelCollectorEndpoint: https://signoz-ingest.mocha.thoughtless.eu
        otelInsecure: false
        presets:
          otlpExporter:
            enabled: true
          loggingExporter:
            enabled: false
        otelAgent:
          config:
            exporters:
              otlphttp:
                tls:
                  insecure: false
                  cert_file: /mtls/cert.pem
                  key_file: /mtls/key.pem
          extraVolumes:
            - name: mtls
              secret:
                secretName: signoz-mtls-client
          extraVolumeMounts:
            - name: mtls
              mountPath: /mtls
              readOnly: true
        otelDeployment:
          config:
            exporters:
              otlphttp:
                tls:
                  insecure: false
                  cert_file: /mtls/cert.pem
                  key_file: /mtls/key.pem
          extraVolumes:
            - name: mtls
              secret:
                secretName: signoz-mtls-client
          extraVolumeMounts:
            - name: mtls
              mountPath: /mtls
              readOnly: true
