apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: litmus
  source:
    repoURL: https://litmuschaos.github.io/litmus-helm
    chart: litmus
    targetRevision: 3.16.0
    helm:
      values: |
        ingress:
          enabled: true
          name: litmus-ingress
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
          ingressClassName: "nginx"
          host:
            name: "litmus.<path:kv/cluster#domain>"
            frontend:
              path: /
              pathType: ImplementationSpecific
          tls:
            - secretName: litmus-tls
              hosts:
                - "litmus.<path:kv/cluster#domain>"
