apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system 
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: ">=1.20.0"
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
