apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: v1.17.2 
    helm:
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: auto
          ingress:
            hosts:
              core: harbor.mocha.thoughtless.eu
            className: ""
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
        externalURL: https://harbor.mocha.thoughtless.eu
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
