apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-turing-0777
  resources:
    requests:
      storage: 100Gi
