apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rustfs-credentials
    creationPolicy: Owner
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: rustfs
        property: access_key
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: rustfs
        property: secret_key
