apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2YYzevKQ/+d0lE1BhMcqhBkkDmpR14LaUq3gu8eGoD6enPLB51dGYg==,iv:AZOQlaqTa2HwUxgm7FXUnuKRH9IzZ4x7HIftJ5cK0cw=,tag:TfK8Ing/ZXNf/pJIqGHZsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9z8z69fa63fa8pnxklq00e8k3556sc233wlp20na7cykthtgvgqwnvej5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVFWK2pQMTJvZGt5U2o5
            SWpOblhRMUUxMDhiOThTQ3hhZzI0YldyVFVzCnZlUlkrT3JQZ3NBT1ZWejM1TEdm
            UG5kVS96bzVZQm9wTXFkT1FHL3kzWUUKLS0tIFdWSnRoWUpBaGNqejkxZW9rNkNU
            bTBjQ1BSYVJOK3VLZG5tWGQyclpWWWsKNmzw2B++gfpn+4tl/bPVRjPQ9w3jgpmS
            RODQMvxhXbMsc+3VVy2NtxW4UY70NtHzvQ6dAFEQwU6ZMiIGLDQMbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T16:26:29Z"
    mac: ENC[AES256_GCM,data:sipxgBZUvP90NA1rVdwcFn6mo6DgLxHcJ6AC0PDFDDFn5culyJPTVmwx6/CrSdskkDVBdK8qy44lZXrEwFwZsmq6JbAtiZDpvxG74olm8Jir4JdP6XijGG6XojuGkMPLzSqusvgWcx2tyaoEMdDX1tlBxX6nukdj4ag77IUt4vw=,iv:t/rr8Z0ZTGfEtZRZb5UXrmAl5pj4SYjvPwLEdKovNIE=,tag:BsYQq6K6BzKH9AJ2G3Rn0A==,type:str]
    pgp: []
    encrypted_regex: ^(chart|password|user|username|api-token)$
    version: 3.8.1
