apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-thoughtless
  namespace: default
spec:
  secretName: wildcard-thoughtless
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer 
  commonName: "*.thoughtless.eu"
  dnsNames:
  - "thoughtless.eu"
  - "*.thoughtless.eu"
