apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel
  data:
  - secretKey: credentials.json
    remoteRef:
      key: cloudflared
      property: credentials.json
