apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-metrics
  namespace: signoz
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: statefulset
  image: otel/opentelemetry-collector-contrib:0.156.0
  serviceAccount: otel-metrics-collector
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  targetAllocator:
    enabled: true
    serviceAccount: otel-metrics-targetallocator
    prometheusCR:
      enabled: true
      serviceMonitorSelector: {}
      podMonitorSelector: {}
      scrapeInterval: 30s
  config:
    receivers:
      prometheus:
        config:
          scrape_configs: []
        target_allocator:
          endpoint: http://otel-metrics-targetallocator
          interval: 30s
          collector_id: ${env:POD_NAME}
    processors:
      resource/cluster:
        attributes:
          - key: k8s.cluster.name
            value: mocha
            action: upsert
      batch: {}
    exporters:
      otlphttp:
        endpoint: http://signoz-otel-collector.signoz.svc.cluster.local:4318
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [resource/cluster, batch]
          exporters: [otlphttp]
