apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: "CloudKube (OVH)"
  eventMetadata:
    env: "production"
    cluster: "Talos"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
    - kind: Kustomization
      name: '*'
