---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/qjoly/GitOps
  ref:
    branch: "cluster/home"
