apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pr-gitops-grafana-annotation
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pr-gitops-grafana-annotation
    creationPolicy: Owner
  data:
    - secretKey: github_webhook_secret
      remoteRef:
        key: pr-gitops-grafana-annotation
        property: github_webhook_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: grafana_token
      remoteRef:
        key: pr-gitops-grafana-annotation
        property: grafana_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
