apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer
  namespace: traefik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: crowdsec-bouncer
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: crowdsec
        property: bouncer_key
