apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: kyoo
    targetRevision: 0.1.5
    helm:
      values: |
        postgresql:
          auth:
            existingSecret: "kyoo-postgresql"
            secretKeys:
              adminPasswordKey: "password"
              userPasswordKey: "password"
        back:
          deployment:
            memoryLimit: 2500Mi
        route:
          enabled: true
          ingress:
            enabled: true
            hostName: kyoo.une-pause-cafe.fr
            extraLabels: {}
            annotations:
              cert-manager.io/cluster-issuer: infomaniak
            tls:
              enabled: true
              secretName: "kyoo-tls"
            ingressClassName: nginx
        volumes:
          media:
            enabled: false
        secrets:
          rabbitmq:
            enabled: false
          kyoo:
            enabled: false
        config:
          data:
            LIBRARY_LANGUAGES: "fr"
        extraResources:
          - apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: nfs
            spec:
              capacity:
                storage: 50Gi
              volumeMode: Filesystem
              accessModes:
                - ReadOnlyMany
              persistentVolumeReclaimPolicy: Retain
              storageClassName: local
              mountOptions:
                - hard
                - nfsvers=4.1
              nfs:
                path: /mnt/Stockage/Plex
                server: 192.168.1.90
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: media
            spec:
              accessModes:
                - ReadOnlyMany
              volumeMode: Filesystem
              resources:
                requests:
                  storage: 50Gi
              storageClassName: local
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: kyoo-postgresql
            spec:
              refreshInterval: "30s"
              secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
              target:
                name: kyoo-postgresql
              data:
              - secretKey: password
                remoteRef:
                  key: kyoo
                  property: postgres-password
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: kyoo-secrets
            spec:
              refreshInterval: "30s"
              secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
              target:
                name: kyoo-secrets
              data:
              - secretKey: postgres-password
                remoteRef:
                  key: kyoo
                  property: postgres-password
              - secretKey: tmdb-api
                remoteRef:
                  key: kyoo
                  property: tmdb-api
              - secretKey: kyoo-apikeys
                remoteRef:
                  key: kyoo
                  property: kyoo-apikeys
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: kyoo-rabbitmq
            spec:
              refreshInterval: "30s"
              secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
              target:
                name: kyoo-rabbitmq
              data:
              - secretKey: rabbitmq_user
                remoteRef:
                  key: kyoo
                  property: rabbitmq_user
              - secretKey: rabbitmq_password
                remoteRef:
                  key: kyoo
                  property: rabbitmq_password
              - secretKey: erlang_cookie
                remoteRef:
                  key: kyoo
                  property: erlang_cookie

  destination:
    server: https://kubernetes.default.svc
    namespace: kyoo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
