apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trmnl-server
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: trmnl-server
  source:
    repoURL: https://github.com/qjoly/gitops.git
    targetRevision: HEAD
    path: mocha/apps/trmnl-server/manifests
