---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris
  namespace: polaris
spec:
  interval: 15m
  chart:
    spec:
      chart: polaris
      version: ">=5.7.3"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system

