---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: ">=8.6.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-community-charts
        namespace: flux-system
