apiVersion: apps/v1
kind: Deployment
metadata:
  name: isponsorblocktv
  namespace: isponsorblocktv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isponsorblocktv
  template:
    metadata:
      labels:
        app: isponsorblocktv
    spec:
      containers:
        - name: isponsorblocktv
          image: ghcr.io/dmunozv04/isponsorblocktv
          volumeMounts:
            - mountPath: /app/data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: isponsorblocktv-pvc
