apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: zot
  source:
    repoURL: http://zotregistry.dev/helm-charts
    chart: zot
    targetRevision: 0.1.89
    helm:
      values: |
        mountSecret: true
        secretFiles:
          htpasswd: |-
            matcha:$apr1$lmwb59pt$A46lqnqnPT0MT8.2oKEp21
        persistence: true
        pvc:
          create: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
          className: "traefik"
          pathtype: ImplementationSpecific
          hosts:
            - host: zot.<path:kv/cluster#domain>
              paths:
                - path: /
          tls:
            - secretName: zot-tls
              hosts:
                - zot.<path:kv/cluster#domain>
