---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
provisioner: local.csi.openebs.io
allowVolumeExpansion: true
