apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 41.0.2
    chart: traefik
    helm:
      values: |
        service:
          enabled: true
          type: ClusterIP
        volumes:
          - name: signoz-mtls-client
            mountPath: /mtls
            type: secret
        metrics:
          prometheus: null
          otlp:
            enabled: true
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            resourceAttributes:
              k8s.cluster.name: turing
            http:
              enabled: true
              endpoint: https://signoz-ingest.mocha.thoughtless.eu/v1/metrics
              tls:
                cert: /mtls/tls.crt
                key: /mtls/tls.key
