apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 35.0.1
    chart: traefik
    helm:
      values: |
        service:
          enabled: true
          type: ClusterIP
