---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
  namespace: freshrss
spec:
  interval: 15m
  chart:
    spec:
      chart: freshrss
      version: ">=1.1.4"
      sourceRef:
        kind: HelmRepository
        name: rubxkube-charts
        namespace: flux-system
  values:
    common:
      ingress:
        enabled: false
      persistence:
        enabled: true
        volumes:
          - name: "data"
            storageClassName: "nfs-csi"
            size: "2Gi"
            containerMount: "/config"
            pvcClaim: ""


