apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  source:
    repoURL: https://charts.chaos-mesh.org
    chart: chaos-mesh
    targetRevision: 2.7.1
    helm:
      values: |
        chaosDaemon:
          runtime: containerd
          socketPath: /run/containerd/containerd.sock
        controllerManager:
          service:
            type: LoadBalancer
        bpfki:
          create: true
        prometheus:
          create: true
          volume:
            storage: 2Gi
            storageClassName: ceph-block
        dashboard:
          securityMode: false
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
            ingressClassName: "traefik"
            hosts:
              - name: "chaosmesh.<path:kv/cluster#domain>"
                tls: true
                tlsSecret: chaos-mesh-tls
