apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-k8s-infra
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz-k8s-infra
  source:
    repoURL: https://charts.signoz.io
    chart: k8s-infra
    targetRevision: 0.16.0
    helm:
      values: |
        global:
          clusterName: mocha
          deploymentEnvironment: production
        otelCollectorEndpoint: http://signoz-otel-collector.signoz.svc.cluster.local:4318
        otelInsecure: true
        presets:
          otlpExporter:
            enabled: true
          loggingExporter:
            enabled: false
        otelDeployment:
          config:
            receivers:
              prometheus:
                config:
                  scrape_configs:
                    - job_name: argocd
                      scrape_interval: 30s
                      static_configs:
                        - targets:
                            - argocd-metrics.argocd.svc.cluster.local:8082
                            - argocd-server-metrics.argocd.svc.cluster.local:8083
                    - job_name: plex
                      scrape_interval: 30s
                      static_configs:
                        - targets:
                            - plex-exporter.plex-exporter.svc.cluster.local:9000
            processors:
              resource/cluster:
                attributes:
                  - key: k8s.cluster.name
                    value: mocha
                    action: upsert
            service:
              pipelines:
                metrics/argocd:
                  receivers:
                    - prometheus
                  processors:
                    - resource/cluster
                    - batch
                  exporters:
                    - otlphttp
