---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - signoz.yaml
  - k8s-infra.yaml
  - dashboard-provisioner.yaml
  - otlp-ingress.yaml
  - otlp-mtls.yaml
  - alerting.yaml
configMapGenerator:
  - name: signoz-dashboards
    namespace: signoz
    files:
      - dashboards/host-metrics.json
      - dashboards/k8s-events-receiver.json
      - dashboards/kubernetes-cluster-metrics.json
      - dashboards/kubernetes-cronjobs.json
      - dashboards/kubernetes-node-metrics-detailed.json
      - dashboards/kubernetes-node-metrics-overall.json
      - dashboards/kubernetes-pod-metrics-detailed.json
      - dashboards/kubernetes-pod-metrics-overall.json
      - dashboards/kubernetes-pvc-metrics.json
      - dashboards/argocd.json
      - dashboards/traefik.json
      - dashboards/plex.json
      - dashboards/zfs-backup.json
      - dashboards/proxmox.json
      - dashboards/rook-ceph.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
