apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  source:
    repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: 0.135.1
    helm:
      values: |
        global:
          storageClass: openebs-lvmpv
        clickhouse:
          persistence:
            enabled: true
            size: 100Gi
          resources:
            requests:
              cpu: 500m
              memory: 8Gi
            limits:
              memory: 24Gi
          files:
            config.d/system_log.xml: |
              <clickhouse>
                <text_log>
                  <ttl>event_date + INTERVAL 3 DAY DELETE</ttl>
                </text_log>
                <latency_log>
                  <ttl>event_date + INTERVAL 3 DAY DELETE</ttl>
                </latency_log>
                <error_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </error_log>
                <query_metric_log>
                  <ttl>event_date + INTERVAL 3 DAY DELETE</ttl>
                </query_metric_log>
                <zookeeper_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </zookeeper_log>
                <aggregated_zookeeper_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </aggregated_zookeeper_log>
                <query_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </query_log>
                <query_thread_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </query_thread_log>
                <query_views_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </query_views_log>
                <part_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </part_log>
                <trace_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </trace_log>
                <metric_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </metric_log>
                <asynchronous_metric_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </asynchronous_metric_log>
                <processors_profile_log>
                  <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
                </processors_profile_log>
              </clickhouse>
        signoz:
          ingress:
            enabled: true
            className: traefik
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
            hosts:
              - host: signoz.mocha.thoughtless.eu
                paths:
                  - path: /
                    pathType: Prefix
                    port: 8080
            tls:
              - secretName: signoz-tls
                hosts:
                  - signoz.mocha.thoughtless.eu
