apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  source:
    repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: 0.133.0
    helm:
      values: |
        global:
          storageClass: openebs-lvmpv
        clickhouse:
          persistence:
            enabled: true
            size: 100Gi
          resources:
            requests:
              cpu: 500m
              memory: 8Gi
            limits:
              memory: 24Gi
        signoz:
          ingress:
            enabled: true
            className: traefik
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
            hosts:
              - host: signoz.mocha.thoughtless.eu
                paths:
                  - path: /
                    pathType: Prefix
                    port: 8080
            tls:
              - secretName: signoz-tls
                hosts:
                  - signoz.mocha.thoughtless.eu
